#!/usr/bin/env python3
"""
Add Quick Reference section to Vela Notion page
"""
import json
import requests

# Load config
with open('.notion-config.json', 'r') as f:
    config = json.load(f)

NOTION_TOKEN = config['notion_token']
VELA_PAGE_ID = config['vela_page_id']
NOTION_VERSION = '2022-06-28'

headers = {
    'Authorization': f'Bearer {NOTION_TOKEN}',
    'Content-Type': 'application/json',
    'Notion-Version': NOTION_VERSION
}

def add_blocks(page_id, blocks):
    """Add multiple blocks to a page"""
    url = f'https://api.notion.com/v1/blocks/{page_id}/children'
    data = {'children': blocks}
    response = requests.patch(url, headers=headers, json=data)
    return response.json()

def heading(level, text):
    heading_type = f'heading_{level}'
    return {
        'object': 'block',
        'type': heading_type,
        heading_type: {'rich_text': [{'text': {'content': text}}]}
    }

def paragraph(text):
    return {
        'object': 'block',
        'type': 'paragraph',
        'paragraph': {'rich_text': [{'text': {'content': text}}]}
    }

def code_block(text, language='bash'):
    return {
        'object': 'block',
        'type': 'code',
        'code': {
            'rich_text': [{'text': {'content': text}}],
            'language': language
        }
    }

def main():
    print("📝 Adding Quick Reference section...")

    # Read .env for Supabase info
    supabase_url = "https://memyqgdqcwrrybjpszuw.supabase.co"

    blocks = [
        heading(1, '⚡ Quick Reference'),

        heading(2, 'Key Links'),
        paragraph(f'Supabase Project: {supabase_url}'),
        paragraph('GitHub Repo: https://github.com/huku-dev/vela'),
        paragraph('Frontend URL: (deploy URL here when available)'),

        heading(2, 'Current Signal Parameters'),
        paragraph('Fast EMA: 9 periods (4-hour candles)'),
        paragraph('Slow EMA: 21 periods (4-hour candles)'),
        paragraph('RSI: 14 periods (4-hour candles)'),
        paragraph('SMA Long-term: 50 periods (daily candles)'),
        paragraph('ADX: 4-hour timeframe'),
        paragraph('Default position size: $1,000 (for paper trades)'),

        heading(2, 'Asset Coverage'),
        paragraph('Currently tracking:'),
        paragraph('• BTC (Bitcoin)'),
        paragraph('• ETH (Ethereum)'),
        paragraph('• HYPE (Hyperliquid)'),
        paragraph('• (Check Supabase "assets" table for full list of enabled assets)'),

        heading(2, 'Data Refresh Intervals'),
        paragraph('Live prices: Every 15 minutes (CoinGecko API)'),
        paragraph('Signals: Generated by backend (frequency TBD)'),
        paragraph('Frontend auto-refresh: Every 15 minutes'),

        heading(2, 'Quick Commands'),
        code_block('# Start development server\nnpm run dev\n\n# Build for production\nnpm run build\n\n# Preview production build\nnpm run preview'),

        heading(2, 'File Structure Cheat Sheet'),
        paragraph('• Signal logic: (backend repo - separate)'),
        paragraph('• UI components: src/components/'),
        paragraph('• Pages: src/pages/'),
        paragraph('• Data fetching: src/hooks/useData.ts'),
        paragraph('• Supabase client: src/lib/supabase.ts'),
        paragraph('• Type definitions: src/types.ts'),

        heading(2, 'Environment Variables'),
        paragraph('Required in .env file:'),
        paragraph('• VITE_SUPABASE_URL'),
        paragraph('• VITE_SUPABASE_ANON_KEY'),
    ]

    add_blocks(VELA_PAGE_ID, blocks)
    print("✅ Quick Reference added!")

if __name__ == '__main__':
    main()
